### ISSUE TITLE
Pausing, fast for-/backward causes song to restart on slimproto/squeezelite players.

### ISSUE THREAD

**Issue by Shogun1978** [music-assistant/support#3451]
### What version of Music Assistant has the issue?

2.4.0b14

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I am currently using a different setup but want to migrate to MA. My setup is a multiroom installation (speakers in the rooms, central amp in the basement). To play music I want to use a raspberry pi with a 7.1 USB sound card, split up the channels and use squeezelite instances for each channel. This works already, but when I want to use these players in MA with the slimproto integration, I get issues. The sound starts from the beginning.
After testing it with a classic SMB share and not the subsonic library, I can rule down it to the subsonic library. Somehow, there is the issue. The SMB share as music provider just causes issues with play/pause after a longer time (something like 10 minutes or more).

### How to reproduce

The song will start from the beginning in the following conditions:

- pause/waiting a few seconds/play
- playing announcements
- fast forward/backward

### Music Providers

- Open Subsonic Media Server Library: primary
- SMB/CIFS: for testing

### Player Providers

picoreplayer / squeezelite player with slimproto

### Additional information

I switched the docker container to log debugging information.

### What version of Home Assistant Core are your running

2025.1.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
What do you mean "The SMB share as music provider just causes issues with play/pause after a longer time" as this is exactly my setup. I just had a local track paused for maybe 20 mins after having the player playing for over an hour and no problems

**Comment by OzGav** [comment]
As per the instructions we don't want DEBUG enabled initially. Please disable DEBUG. Restart MA. Get the problem to occur. Wait a few minutes then attach the log.

**Comment by Shogun1978** [comment]
I completely deleted all files and the complete setup of MA. Then I set up all new :-) I think, it's related to the Subsonic connector. After reinstalling the MA I can't play anything from the subsonic system at all. The subsonic library is accessable and I can see all media. Here is the error log:

[error-log-ma.txt](https://github.com/user-attachments/files/18424686/error-log-ma.txt)

**Comment by OzGav** [comment]
Thanks. @khers ^^^^^

**Comment by Shogun1978** [comment]
Thanks for your great support guys! Highly appriciated! And sorry, if I don't deliver all details on first try or wrong infos.
If there is anything I can test, just tell me.

**Comment by MV1707** [comment]
Similar issue with Sonos. After pausing and later resuming, the paused track will indeed resume but after +/- 30 seconds the track will go back to the beginning.

**Comment by MV1707** [comment]
Similar issue with Sonos. After pausing and later resuming, the paused track will indeed resume but after +/- 30 seconds the track will go back to the beginning.

**Comment by OzGav** [comment]
@MV1707 Please don't confusing things with "similar" issues. We need to fix one thing at a time. This is your issue https://github.com/music-assistant/support/issues/3274

**Comment by khers** [comment]
> I completely deleted all files and the complete setup of MA. Then I set up all new :-) I think, it's related to the Subsonic connector. After reinstalling the MA I can't play anything from the subsonic system at all. The subsonic library is accessable and I can see all media. Here is the error log:
> 
> [error-log-ma.txt](https://github.com/user-attachments/files/18424686/error-log-ma.txt)

There were errors in the build for beta 14, please try 15 (it is working for me, including seeking and pausing)

**Comment by OzGav** [comment]
@Shogun1978 please confirm that has been fixed in beta 18

**Comment by Shogun1978** [comment]
@OzGav: tested it with beta 18, still not working. I still believe, it might be some issue in connection to the subsonic provider. I am using Navidrome for my music collection. On my smartphone I use Symfonium for streaming, which works. Also the connection from MA to Navidrome works, I get all covers etc.

I will try with a SMB share or NFS (mounted on system level and passed through to the docker container) later.

**Comment by OzGav** [comment]
Navidrome seems to be a common factor with many issues. @khers any more thoughts?

P.S.  Keep to the one thing per report please

**Comment by Shogun1978** [comment]
Ok, I will try some other things around the FLAC topic and open a new ticket when I have more information. But I might have an idea...

**Comment by khers** [comment]
I cannot reproduce this on my home setup, but that is using subsonic to talk to gonic with sonos speakers. I am listening to an 18 minute track encoded in FLAC using libflac. I played about 30 seconds then paused and let it sit for a minute and then moved the play position forward to the middle of the track. This worked fine. So I paused it again and immediate moved closer to the beginning and that also worked.

Are you using the provider option: 'Force player provider seek'?  I suspect that Navidrome has the same bug as gonic in that it advertises the transcodeOffset field in the seek method but doesn't honor it unless it is transcoding.

**Comment by Shogun1978** [comment]
> I cannot reproduce this on my home setup, but that is using subsonic to talk to gonic with sonos speakers. I am listening to an 18 minute track encoded in FLAC using libflac. I played about 30 seconds then paused and let it sit for a minute and then moved the play position forward to the middle of the track. This worked fine. So I paused it again and immediate moved closer to the beginning and that also worked.
> 
> Are you using the provider option: 'Force player provider seek'? I suspect that Navidrome has the same bug as gonic in that it advertises the transcodeOffset field in the seek method but doesn't honor it unless it is transcoding.

The "Force player provider seek worked for me! Thanks!
