### ISSUE TITLE
Announcements not working when player is off and auto resume has been configured

### ISSUE THREAD

**Issue by bezigebever** [music-assistant/support#3468]
### What version of Music Assistant has the issue?

2.3.6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

When playing an announcement, using the service mucsic_assistant.play_announcement with url pointing to the www folder of HA (e.g. http://x.x.x.x:8123/local/audio/chimes-melody.mp3) to a player that is in off state and has the auto resume on power active, the player resumes the queue and doesn't play the announcement.
Disabling resume solves the problem, the player gets powered on plays the annopuncement and powers off.
When the player is on and playing, it also works.

### How to reproduce

Player in off state with resume configured and something in the queue.
Then the announcement won't work.

### Music Providers

Music assistant
Radio browser
Spotify

### Player Providers

Sonos S1
Slimproto

### Full log output

No error in the log file:

2025-01-16 16:52:28.358 INFO (MainThread) [music_assistant.players] Playback announcement to player Keuken (with pre-announce: None): http://x.x.x.x:8123/local/audio/chimes-melody.mp3

### Additional information

Discussed on Discord with @marcelveldt 

### What version of Home Assistant Core are your running

2025.1.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Please test this again when 2.4.0 ships shortly

**Comment by OzGav** [comment]
@bezigebever 2.4.0 has been released. Please confirm this is fixed

**Comment by OzGav** [comment]
We will close this soon assuming fixed

**Comment by bezigebever** [comment]
I was able to test. The player start playing the music in the queue, no the notification sound...
Issue still there.

**Comment by bezigebever** [comment]
@OzGav can you re-open ?

**Comment by OzGav** [comment]
Please confirm this affects both the Sonos S1 and squeezelite players.

**Comment by bezigebever** [comment]
I have decomissioned the squeezelite players meanwhile, so can only confirm for Sonos S1.

**Comment by OzGav** [comment]
Does the Sonos device support power? What setting is the default in the player controls for power for that device?

**Comment by bezigebever** [comment]
The device uses 'Fake power control'

**Comment by OzGav** [comment]
@bezigebever Please confirm this has been fixed in 2.5.0

**Comment by OzGav** [comment]
This will be closed soon due to no follow up
