### ISSUE TITLE
'Please call connect first' error requires reauthification with home assistant systematically

### ISSUE THREAD

**Issue by gribouk** [music-assistant/support#3512]
### What version of Music Assistant has the issue?

2.3.6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

I can use music assistant for some time after reauthification with home assistant. At some point, sometimes after docker restarted, I discover that I cannot play music through HA players and the error from the title returned. It takes me to reauthificate with HA again and save for MA to restart working again. It creates long lived tokens each time, which is suppossed to provide access for years, not days! And in a few weeks it repeats all over again...

### How to reproduce

Reproducing is cumbersome as it is not clear why exactly it looses access to the HA. Most frequently, but not always, it was in the vicinity of containers manual restart or rebuild, which is common practice on container update...

### Music Providers

Local Storage, Radio Sttions ...

### Player Providers

Home Assistant

### Full log output

[musicassistant.log](https://github.com/user-attachments/files/18574605/musicassistant.log)

### Additional information

none

### What version of Home Assistant Core are your running

2024.1.2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Can you provide more detail about exactly how you have installed HA and MA

**Comment by gribouk** [comment]
They are both running docker containers on same machine.

**Comment by gribouk** [comment]
P.S. I have been removing and re running the containers for HA for some time today to see if it really related, but at the moment it had no effect on the connectivity. It is somehow related to the time - if a couple of the auth is a week or so old, then I see that error wich can only be resolved through the reathification...

**Comment by OzGav** [comment]
We have never seen this type of report before so continue to investigate your end until this can be looked at further.

**Comment by gribouk** [comment]
Here comes the fresh one. I was updating the network relacing the router. Neither MA nor HA were rebooted, only the router. And then comes below:

2025-02-01 20:09:12.178 INFO (MainThread) [music_assistant.hass] Connection to HA lost. Connection will be automatically retried later.
2025-02-01 20:09:45.485 WARNING (MainThread) [music_assistant] Error loading provider(instance) Home Assistant: Cannot connect to host tigraresidence.duckdns.org:443 ssl:default [Timeout while contacting DNS servers] (will be retried later)
2025-02-01 20:12:41.395 ERROR (MainThread) [ffmpeg.711] Stream error: Timeout on reading data from socket
2025-02-01 20:12:41.420 WARNING (MainThread) [asyncio] child process pid 711 exit status already read:  will report returncode 255
2025-02-01 20:13:00.557 WARNING (MainThread) [music_assistant] Error loading provider(instance) Home Assistant: Cannot connect to host tigraresidence.duckdns.org:443 ssl:default [Timeout while contacting DNS servers] (will be retried later)
2025-02-01 20:13:36.464 ERROR (MainThread) [ffmpeg.710] Stream error: 'NoneType' object has no attribute 'get_player_config_entries'
2025-02-01 20:15:00.743 INFO (MainThread) [music_assistant] Loaded plugin provider Home Assistant
2025-02-01 20:15:00.988 INFO (MainThread) [music_assistant] Loaded player provider Home Assistant MediaPlayers
2025-02-01 20:16:33.799 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Tigra Music - crossfade: False
2025-02-01 20:16:33.828 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Tigra Music - crossfade: False
2025-02-01 20:27:41.371 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_pause: Please call connect first.
2025-02-01 20:27:43.827 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_pause: Please call connect first.
2025-02-01 20:27:47.411 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_pause: Please call connect first.
2025-02-01 20:27:48.321 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_pause: Please call connect first.
2025-02-01 20:28:06.378 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_pause: Please call connect first.
2025-02-01 20:28:09.897 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_pause: Please call connect first.
2025-02-01 20:28:10.682 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_pause: Please call connect first.
2025-02-01 20:28:12.429 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_pause: Please call connect first.
2025-02-01 20:28:13.693 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_pause: Please call connect first.
2025-02-01 20:28:14.740 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_pause: Please call connect first.
2025-02-01 20:28:55.124 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_pause: Please call connect first.
2025-02-01 20:28:56.103 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_pause: Please call connect first.
2025-02-01 20:30:35.247 ERROR (MainThread) [ffmpeg.775] Stream error: Timeout on reading data from socket
2025-02-01 20:31:23.177 WARNING (MainThread) [music_assistant.webserver] Disconnected: Received non-Text message.
2025-02-01 20:31:23.177 WARNING (MainThread) [music_assistant.webserver] Disconnected: Received non-Text message.
2025-02-01 20:47:45.177 WARNING (MainThread) [music_assistant.webserver] Disconnected: Received non-Text message.
2025-02-01 20:47:46.176 WARNING (MainThread) [music_assistant.webserver] Disconnected: Received non-Text message.
2025-02-01 20:59:11.591 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_pause: Please call connect first.
2025-02-01 21:38:51.178 WARNING (MainThread) [music_assistant.webserver] Disconnected: Received non-Text message.
2025-02-01 21:38:56.176 WARNING (MainThread) [music_assistant.webserver] Disconnected: Received non-Text message.
2025-02-01 21:50:04.471 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_pause: Please call connect first.
2025-02-01 21:50:24.204 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_pause: Please call connect first.

**Comment by OzGav** [comment]
Did you want that URL in the log above? Also are you trying to access MA using SSL?

**Comment by gribouk** [comment]
tigraresidence.duckdns.org ?

I am not sure I fully get the question.

In ngnx proxy manager I have a host tigra_music.tigraresidence.duck_dns.org to access MA from the outer world, but it does not access MA using SSL. to the extent of my understanding of how proxy manager works. Moreover I have introduced it like couple of weeks or less ago, while this problem is from December or earlier. 

The domain above is for HA access.

**Comment by marcelveldt** [comment]
This seems to be the source of all issues:
Cannot connect to host tigraresidence.duckdns.org:443 ssl:default [Timeout while contacting DNS servers]

So dns resolution (at least from the perspective of the MA container) seems to break.
Can you just try to let MA connect to HA on the local IP ?

**Comment by gribouk** [comment]
Yes, it should solve the puzzle in the case of ngnx proxy manager. I remembered why I started to auth with duckdns in the first place - I used duckdns HA addon to mantain the certificates in the beggining, few month ago. If you use that addon, you have to access HA via https only since you change http settings in the config, unlike with ngnx. So, I started this practice and the problem did not take long to wait. When I switched to ngnx the need of addressing the HA via https had been gone, but I kept this part as it was. However, if someone is using https access to HA for some reasons, this path would not be aplicable.  In the mean time I have done the following:

In my router setting in the DNS section I have added the records for my domain and all subdomains * of it to point to the ngnx server. And it feels that it started to work much better. Atleast I stopped experiencing delays uppon referencing the nodes and messages of DNS failures. Maybe it would be the solution for those, who needs https access, time will tell. Until then, this issue may be considered as closed.

**Comment by muttleydosomething** [comment]
I too am having the same error. I've restarted HA several times. I've reloaded the integration, reloaded and restarted. 
I'm using an Odriod N2+. HASOS


A Restart of the OS fixed it! But still don't know what caused it. HA and all add-ons, integrations were working fine - except for MA

These were my logs.

Logger: homeassistant.components.websocket_api.http.connectionSource: components/websocket_api/commands.py:250integration: Home Assistant WebSocket API (documentation, issues)First occurred: 20:35:58 (1 occurrence)Last logged: 20:35:58[281472650492992] Unexpected exceptionTraceback (most recent call last):  File "/usr/src/homeassistant/homeassistant/components/music_assistant/media_player.py", line 134, in wrapper    return await func(self, *args, **kwargs)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/src/homeassistant/homeassistant/components/music_assistant/media_player.py", line 325, in async_media_play    await self.mass.players.player_command_play(self.player_id)  File "/usr/local/lib/python3.13/site-packages/music_assistant_client/players.py", line 64, in player_command_play    await self.client.send_command("players/cmd/play", player_id=player_id)  File "/usr/local/lib/python3.13/site-packages/music_assistant_client/client.py", line 252, in send_command    return await future           ^^^^^^^^^^^^music_assistant_models.errors.PlayerCommandFailed: Please call connect first.The above exception was the direct cause of the following exception:Traceback (most recent call last):  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 250, in handle_call_service    response = await hass.services.async_call(               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    ...<7 lines>...    )    ^  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call    response_data = await coro                    ^^^^^^^^^^  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service    return await target(service_call)           ^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call    single_response = await _handle_entity_call(                      ^^^^^^^^^^^^^^^^^^^^^^^^^^        hass, entity, func, data, call.context        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    )    ^  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call    result = await task             ^^^^^^^^^^  File "/usr/src/homeassistant/homeassistant/components/music_assistant/media_player.py", line 137, in wrapper    raise HomeAssistantError(error_msg) from errhomeassistant.exceptions.HomeAssistantError: Please call connect first.
