### ISSUE TITLE
Provider slimproto already loaded and only one instance allowed

### ISSUE THREAD

**Issue by freakyjoe8** [music-assistant/support#3587]
### What version of Music Assistant has the issue?

2.4.0rc4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

I cannot add slimproto as player provider. When I click save I get the error message: "Provider slimproto already loaded and only one instance allowed."

### How to reproduce

Add slimproto as player provider and click "save".

### Music Providers

none

### Player Providers

slimproto

### Full log output

[d5369777_music_assistant_beta_2025-02-18T20-59-38.655Z.log](https://github.com/user-attachments/files/18854417/d5369777_music_assistant_beta_2025-02-18T20-59-38.655Z.log)

### Additional information

none

### What version of Home Assistant Core are your running

2025.2.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
So, to ask the obvious question... Is it already added as provider ?

**Comment by freakyjoe8** [comment]
Not from what I can see in the UI:

![Image](https://github.com/user-attachments/assets/7b0b301d-68d0-4e6a-909c-92a854e170ef)

**Comment by OzGav** [comment]
You haven’t attached the full log. Explain how you got to this situation. New install, upgrade from beta version xxx etc. Explain this in detail.

**Comment by marcelveldt** [comment]
can reproduce this issue - will be fixed soon

**Comment by marcelveldt** [comment]
fixed in 2.4.0rc5

**Comment by freakyjoe8** [comment]
I tried rc6 and I still get the same error. Shall I try to reinstall MA? Might be that this would solve the issue but the root cause might also be gone then.

**Comment by OzGav** [comment]
If you are happy to then yes try that

**Comment by marcelveldt** [comment]
It could also be that the error is misleading and something else happened.
Maybe you also got something running on port 9000 or maybe have the slimproto integration setup in HA ?

**Comment by freakyjoe8** [comment]
it works now with rc7. Though I've also reinstalled it from scratch. Other than that I didn't change anything.
