### ISSUE TITLE
'NoneType' object has no attribute 'display_name'

### ISSUE THREAD

**Issue by shaiger** [music-assistant/support#3789]
### What version of Music Assistant has the issue?

2.5.0b18

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

I cannot play TTS on Snapcast players. Everything seems to work fine on Google cast devices.
I get the following error: 'NoneType' object has no attribute 'display_name'

### How to reproduce

Either from an automation, or by using the dev console (actions).
Action YAML:

```
action: tts.speak
target:
  entity_id: tts.google_cloud
data:
  cache: false
  media_player_entity_id: media_player.office_display_cast
  message: Using a Snapcast player
```

### Music Providers

N/A (TTS)

### Player Providers

Snapcast

### Full log output

[MA Logs.txt](https://github.com/user-attachments/files/19508392/MA.Logs.txt)

### Additional information

 - Everything seems to work fine on Google Cast devices.
 - Playing mp3 from local storage works, the problem is limited to TTS
 - I tried different TTS engines including piper (on device)
I suspect this has started happening at the same time Snapcast players started to explicitly refuse accepting pause commands but I am not sure.
The problem is very easy to reproduce, and I am on the beta channel - more than happy to test potential fixes.

### What version of Home Assistant Core are your running

core-2025.3.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

### Have you included ALL of the information specified in the Troubleshooting FAQ or explained why you cannot

- [x] Yes

**Comment by OzGav** [comment]
As requested in the template instructions don’t paste walls of text, and that isn’t the full MA log. Please edit your post to remove what you have and replace with what we need.

**Comment by shaiger** [comment]
Hi @OzGav - sorry for the misunderstanding. 
I have removed the content initially posted.  The attached log file is slightly sanitized (family member names, ip addresses, etc).

**Comment by OzGav** [comment]
This is confirmed and will be looked at soon.

**Comment by ronluna** [comment]
Having the same problem when using music_assistant.play_announcement

```
data:
  url: https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3
  announce_volume: 5
  use_pre_announce: true
action: music_assistant.play_announcement
target:
  entity_id: media_player.ma_living_room_sc6_c1
```

**Comment by OzGav** [comment]
This should be fixed in 2.5.1, or 2.6.0b4 (when released)

**Comment by stnokott** [comment]
Looks fixed with 2.5.1

**Comment by jojo141185** [comment]
Hi,

I'm still experiencing the same issue with version **2.5.1**.

I was able to start playback on my Snapcast player without any problems. However, when I try to pause the music via the Web UI, I consistently get the following error:

```
'NoneType' object has no attribute 'identifier'
```

### Relevant error log from Music Assistant:

```
2025-04-24 20:10:11.682 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_pause: 'NoneType' object has no attribute 'identifier'
```

### Snapserver log:

```
2025-04-24 20-10-11.682 [Error] (Server) Server::onMessageReceived JsonRequestException: {"error":{"code":-32603,"data":"Stream not found","message":"Internal error"},"id":996,"jsonrpc":"2.0"}, message: {"id":996,"jsonrpc":"2.0","method":"Group.SetStream","params":{"id":"dd1b682c-7b66-ce56-3050-2167e1e4d0ed","stream_id":"default"}}
```

I'm using an **external Snapserver instance (v0.31.0)** with a custom configuration.

---

### ✅ Solution

The issue seems to be caused by the **lack of a stream named `default`** in the Snapserver configuration. Music Assistant appears to expect this stream name when attempting to manage playback (e.g., pause/resume).

To fix this, make sure your `snapserver.conf` includes a stream named `default`. Example configuration:

```ini
[stream]
source = pipe:///tmp/snapfifo?name=default&sampleformat=48000:16:2&codec=flac
```

After updating the config, restart Snapserver.

---

This requirement might be worth explicitly mentioning in the documentation (unless I missed it). Could help others avoid running into the same issue. 😊

Thanks! 🙏

**Comment by OzGav** [comment]
BETA 4 has been released which fixes this. As this has been reported fixed with the same patch in 2.5.1 this will be closed.
