### ISSUE TITLE
Spotify Connect Pauses

### ISSUE THREAD

**Issue by floodwayprintco** [music-assistant/support#3952]
### What version of Music Assistant has the issue?

2.5.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

I've been chasing this issue a couple different ways but finally turned the logs on. I think I see some relevant info but not sure what to make of it.

Long story short, Spotify Connect will eventually pause. It seems like I gotta fully restart Music Assistant to make it work.

I am wondering if my log gives any hints. There's not much action before this when it's playing fine.

`{'event_time': '2025-05-02 12:57:43.092470', 'event': 'playing', 'track_id': '2tXsQ0HUXLvOlrKEwiTQjv', 'position_ms': '0'}
2025-05-02 13:00:18.050 DEBUG (MainThread) [music_assistant.spotify_connect] Received metadata on webservice: 
{'event_time': '2025-05-02 13:00:18.026560', 'event': 'preload_next', 'track_id': '2tXsQ0HUXLvOlrKEwiTQjv'}
2025-05-02 13:00:18.117 DEBUG (MainThread) [music_assistant.spotify_connect] [2025-05-02T18:00:18Z INFO  librespot_playback::player] Loading <Mr Spinner> with Spotify URI <spotify:track:1H2DnLozfZzBJG4GjSDHXA>
2025-05-02 13:00:18.820 DEBUG (MainThread) [music_assistant.spotify_connect] [2025-05-02T18:00:18Z INFO  librespot_playback::player] <Mr Spinner> (119167 ms) loaded
2025-05-02 13:00:19.161 DEBUG (MainThread) [music_assistant.spotify_connect] Received metadata on webservice: 
{'event_time': '2025-05-02 13:00:19.138138', 'event': 'preloading', 'track_id': '1H2DnLozfZzBJG4GjSDHXA'}
2025-05-02 13:23:38.250 DEBUG (MainThread) [music_assistant.spotify_connect] [2025-05-02T18:23:38Z WARN  librespot_connect::state::context] couldn't load context info because: context is not available. type: Default
2025-05-02 13:23:38.250 DEBUG (MainThread) [music_assistant.spotify_connect] [2025-05-02T18:23:38Z WARN  librespot_core::dealer] No subscriber for msg.uri: playback-settings/content-settings-update
2025-05-02 13:24:00.319 DEBUG (MainThread) [music_assistant.spotify_connect] [2025-05-02T18:24:00Z INFO  librespot_connect::spirc] device became inactive`

### How to reproduce

Let Spotify Connect play for a while and it will pause. Reloading Airplay or the Spotify Connect doesn't fix it, only a full restart of the addon.

### Music Providers

I am only using the PLUGIN Provider for Spotify Connect.

### Player Providers

Airplay, casting to three Airport Express that are hard-wired ethernet.

### Full log output

[d5369777_music_assistant_2025-05-02T18-31-31.117Z.log](https://github.com/user-attachments/files/20016916/d5369777_music_assistant_2025-05-02T18-31-31.117Z.log)

### Additional information

Reloading Airplay, or Spotify Connect doesn't let it play again. It will work instantly after restarting the add-on.

### What version of Home Assistant Core are your running

2025.4.3

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

### Have you included ALL of the information specified in the Troubleshooting FAQ or explained why you cannot

- [x] Yes

**Comment by OzGav** [comment]
Why do you say it pauses? Do you see the player bar icon change?

**Comment by tomashejatko** [comment]
Hello, I have same issue. Streaming to Fully Kiosk device.
After few minutes, music from Spotify stops to play, but player inside MA seems to be still playing.
I don't need to restart anything, I go to Spotify app on my Android phone, plays something else and it starts to stream again... and after some time, stops again.

Please, if I can provide any meaningful logs or can anyhow help with debug, let me know, I'd like to help you debug as much as I can :)

**Comment by tomashejatko** [comment]
Another symptom: in Logbook I see two entries about device exported from MA to HA:

1. changed to Idle
2. changed to Playing

But music stops at that moment

**Comment by Tazmanian79** [comment]
I have the same issue when playing radio's from TuneIn.  After X time the player pauses.  But the pause is not triggered by anything.  It just says paus.  

As you can see this is my log from Home Assistant.
![Image](https://github.com/user-attachments/assets/3f670ec2-e0f0-4981-a750-8b6609814817)

The time is random.
Last week it paused always after +- 1 min.  I tried starting the radio from music assistant, home assistant or from the play button on my Sonos device.  All had the same behaviour.
It was only fixed after a restart of the music assistant container.

But in the logs of music assistant I see the following error:
2025-05-08 18:22:25.028 ERROR (MainThread) [aiosonos.api] Received unhandled error: {'namespace': 'playback:1', 'householdId': 'Sonos_JFy0KEiPz2ufhiKai3lIEK5TcV.Hnu6KKAp8O-Hf6FesQJO', 'locationId': 'lc_45db6ee0ef25416f834c86c202192394', 'groupId': 'RINCON_949F3E52B01601400:514327593', 'name': 'playbackError', 'type': 'playbackError'}: {'_objectType': 'playbackError', 'errorCode': 'ERROR_PLAYBACK_FAILED', 'reason': 'ERROR_CORRUPT_FILE', 'itemId': '02a5b9ecfbd74b5085afbcb383a592f7', 'queueVersion': '1746721091', 'serviceId': 0, 'serviceName': '10.52.0.100:8097', 'trackName': 'Music Assistant'}

**Comment by floodwayprintco** [comment]
Sorry for not replying sooner. 

I gave up on trying to use the Spotify UI with Connect, I just call playlists through MusicAssistant now. 

The pausing and being unable to start a playlist has been an issue for a long time and I've tried a LOT of stuff to solve it. There seems to be a limitation with being able to wake up Spotify Connect devices that prevents me from starting in the music in the morning as well, so I have kinda moved on. 

I would still love to see Connect working though so I will at least try to help troubleshoot.

I should note I also had a saturated network from a lot of cameras. They're on a VLAN now so that could solve my DNS issues but again, still can't wake it up without a bunch of hoops to jump through.

> Why do you say it pauses? Do you see the player bar icon change?

Yes, everything flips to paused. I noticed the elapsed time on Spotify gets stuck. 

Seems like the Connect player gets stuck first.

I had the same issues with Forked-Daapd / Owntone with Spocon. A lot of the same libraries that Music Assistant uses. I had continues issues with Connect pausing and not being able to wake it up.

I blame Spotify honestly. 

I'd rather see effort diverted into a Spotify skin for the UI, haha!

**Comment by OzGav** [comment]
The beta version is a separate version of the server which you can run in parallel. https://www.music-assistant.io/release/

**Comment by DJ1TJOO** [comment]
I'm running MA, MA beta and a librespot instance on a separate machine.

Currently none are showing up in the Spotify speaker list. (Chromecasts do still show). Even Sonos directly is not showing in Spotify.

I'll see if I can find out what the problem is (probably something locally wrong) and then will give feedback on the beta channel

**Comment by DJ1TJOO** [comment]
No sorry, did not have the time yet to look at it. Since the last librespot update the Librespot instance on the standalone machine is working again. 

However for MA it is still not showing up, so I cannot test it

**Comment by OzGav** [comment]
OK we have updating the librespot version high on to the todo list

**Comment by OzGav** [comment]
Librespot has been bumped. Please advise if this is fixed when beta 17 is released.

**Comment by OzGav** [comment]
Beta17 has been released, please confirm this has been fixed.

**Comment by DJ1TJOO** [comment]
Still does not work

- Spotify app recognises the MA Spotify connect provider
- Spotify app can connect to MA provider 
- MA recognises which song is being played and is shown in the UI

No sounds is produced on the speakers 

In the Spotify app the music is paused after around 10s

I did see an error in the logs but I'm not experienced enough to know if it is related

MA version: 2.7.0b21 via addon
HA version: 
Installation method
Home Assistant OS
Core
2025.12.1
Supervisor
2025.12.2
Operating System
16.3
Frontend
20251203.1
Companion app
2025.12.1 (2025.1546)

Providers:
- default providers
- Sonos provider (1 speaker)
- Spotify connect provider for the Sonos speaker

[d5369777_music_assistant_beta_2025-12-06T21-43-47.707Z.log](https://github.com/user-attachments/files/24000545/d5369777_music_assistant_beta_2025-12-06T21-43-47.707Z.log)

**Comment by DJ1TJOO** [comment]
I have some updates on the latest version of the beta: 2.8.0b4

Everything for spotify connect provider seems to be fine to ma web.
Playing to sonos s1 from the ma web is also fine.

But spotify connect provider for sonos s1, is not working. 
Should I open a seperate issue for it since, this direct problem seems to be fixed?

Do you have suggestions on what I already could try before possible opening a new issue?

**Comment by OzGav** [comment]
Define “is not working”

**Comment by OzGav** [comment]
Open a new issue. Make it clear what other player providers you have tried that do or don’t show the problem. Make sure you try different music providers as well, particularly radio.

**Comment by MarvinSchenkel** [comment]
Reading through this and the remaining issues are the same as this one: https://github.com/music-assistant/support/issues/4735

Closing this one as the other issue represents the issue more clearly: No sound on Sonos.
