### ISSUE TITLE
Browsing Tracks in Tidal/Spotify gives error: "cannot access local variable 'library_items' where it is not associated with a value"

### ISSUE THREAD

**Issue by SteffanDonal** [music-assistant/support#3979]
### What version of Music Assistant has the issue?

2.5.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

When clicking the "Tracks" folder under browse, Tidal (for example), no items are shown, and an error pops up in the snackbar:
`cannot access local variable 'library_items' where it is not associated with a value`

### How to reproduce

Browse > [Provider] > Tracks

### Music Providers

Tidal, Spotify

Note - I have two accounts logged into Spotify, and only one of them shows this error. The other simply shows no tracks at all (only the 'Go Up' item), but no error.

### Player Providers

N/A, issue is not affecting playback.

### Full log output

Note: It is the second Spotify account (`Alice アリス`) that does not show an error, if at all helpful.
In these logs, Tidal and the Web Server have been changed to `debug` logging.

[music-assistant.log](https://github.com/user-attachments/files/20124723/music-assistant.log)

### Additional information

- It doesn't matter which music provider is currently in use, the behavior does not change.
- It doesn't matter which player provider is currently in use, the behavior does not change.
- No grouping.
- Playback is being done through the UI.
- Container, using the `docker-compose` configuration provided by MA, with host networking mode.
- Browsing tracks appears to work fine for local files and Music Assistant.
- Clearing my browser cache didn't change anything, nor did trying a different browser.

### What version of Home Assistant Core are your running

N/A

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

### Have you included ALL of the information specified in the Troubleshooting FAQ or explained why you cannot

- [x] Yes

**Comment by OzGav** [comment]
Confirmed

**Comment by robsonke** [comment]
I have the same issue with the Soundcloud provider (latest beta). I tried to reproduce it with the latest dev code but so far no success.

**Comment by OzGav** [comment]
@robsonke will this re-occur or is it solved by clearing the cache?

**Comment by robsonke** [comment]
No, I tried this morning and the issue is back. A stacktrace would be nice though, it's hard to guess where it's coming from and might be solved on dev already.

**Comment by OzGav** [comment]
Ok will have to wait for this one to get to the top of the pile.

**Comment by fmunkes** [comment]
I guess I just found that one by accident while looking at type hinting the music provider

**Comment by SteffanDonal** [comment]
Happy to confirm that this is fixed for me in the latest beta build.

**Comment by robsonke** [comment]
Yes, same here. works again.
