### ISSUE TITLE
Tidal provider issue

### ISSUE THREAD

**Issue by cmonrroy88** [music-assistant/support#4045]
### What version of Music Assistant has the issue?

2.5.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

Since yesterday I am having trouble syncing my Tidal library in music assistant.

It only syncs 49 songs out of more than 500 that I have stored in my account.

I have it installed through home assistant, I checked logs and there are no related errors.

I've tried restarting the add-on, logging back into the Tidal integration but it hasn't worked. any ideas what might be happening?

I also tried deploying music assistant outside of home assistant and it went from syncing 49 songs to 59 songs.

### How to reproduce

1. Deploy music assistant with home assistant or docker
2. Enable tidal provider
3. Sync music
4. Evaluate the difference in tracks between music assistant and Tidal

### Music Providers

I only use tidal provider

### Player Providers

Squeezelite

### Full log output

[logs.txt](https://github.com/user-attachments/files/20647252/logs.txt)

### Additional information

Initially I had problems with my local dns, but after restarting the integration and my dns, the error disappeared from the logs but the synchronization problem persists.

### What version of Home Assistant Core are your running

2025.5.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

### Have you included ALL of the information specified in the Troubleshooting FAQ or explained why you cannot

- [x] Yes

**Comment by cmonrroy88** [comment]
I just enabled debug logs for the provider and the controller and apparently it is performing the requests correctly towards Tidal.

However, when I check the track library, it is still the same 49 songs.


Last night I tried integrating Qobuz and had no problem, so far the issue is only with Tidal.

[logs-1.txt](https://github.com/user-attachments/files/20655822/logs-1.txt)

**Comment by OzGav** [comment]
OK lets eliminate any variables. Do a database reset MA SETTINGS >> MUSIC CONTROLLER >> ADVANCED and then sync Tidal and see what the log shows. There are some skipped items showing in your log but not 450 of them...

**Comment by cmonrroy88** [comment]
There, this was the result of the tests.

First, I cleaned the database and immediately started to synchronize each provider, giving as a result:

1. Qobuz: 486 songs
2. Tidal: 48 songs
3. Music assistant: 0 songs

Note: in both Qobuz and Tidal I have the same songs (I migrated my library from Tidal to Qobuz for these tests).

Afterwards, I deactivated the Qobuz provider and cleaned the database again, resulting in:

1. Tidal: 48 songs
2. Music assistant: 0 songs

I attach the logs corresponding to both attempts.

[d5369777_music_assistant_2025-06-10T17-30-06.020Z.log](https://github.com/user-attachments/files/20677308/d5369777_music_assistant_2025-06-10T17-30-06.020Z.log)

**Comment by cmonrroy88** [comment]
I used this app to copy my library from Tidal to Qobuz. 

https://soundiiz.com/

**Comment by OzGav** [comment]
Does anything else from Tidal appear in its entirety? Playlists, albums, artists or tracks? Can you search Tidal without issue from the global search page? Is there anything unusual about your account, your network setup or anything else. No else is reporting this and the fact that you aren't seeing anything from two different providers suggests something at your end.

**Comment by OzGav** [comment]
Confirm that your Tidal collection of tracks looks something like this 

![Image](https://github.com/user-attachments/assets/b5b7597e-126e-4435-a17b-692ece301ad7)

**Comment by cmonrroy88** [comment]
The global search and playlist works fine, it's looks that the issue is only with favorite tracks.

This is my library in Tidal, no problems there

![Image](https://github.com/user-attachments/assets/367a90d7-15a7-4ee0-b96b-30f6fc1f1e88)

But, if I search some song of the latest added, i.e. Down Under, looks like I haven't this song in my library, but it is

![Image](https://github.com/user-attachments/assets/124c46f4-f89b-4c84-904a-6c70888a8dbc)

I also notice that the sync job "stops" at the B
![Image](https://github.com/user-attachments/assets/1e821027-3d13-4487-97ee-2b597fc823d5)

**Comment by OzGav** [comment]
There is a lot of throttling going on as shown in the log. If you try and sync again do any more get pulled in?

**Comment by SteffanDonal** [comment]
I am also seeing this exact issue - only 49 tracks listed under Tidal/Browse/Tracks: [music-assistant-tidal-tracks.log](https://github.com/user-attachments/files/20690052/music-assistant-tidal-tracks.log)

**Comment by OzGav** [comment]
@jozefKruszynski

**Comment by jozefKruszynski** [comment]
I'll take a look when I'm back from holidays.
One thing to mention though, the logs show a mix of deleting from db and synching the database. You shouldn't deal with the music providers this way.
When removing a provider you need to wait until the deletion is fully completed, there is log message that will say that the removal is complete, after this you should restart the MA addon and then a further cleanup operation happens, in case some stuff was left over.
Only after this second operation is compete should you attempt to add the provider again.

https://www.music-assistant.io/music-providers/?h=remove+pro

If this still fails and only synchs 49 tracks, then we absolutely have an issue.

**Comment by cmonrroy88** [comment]
i followed the steps that @jozefKruszynski mentioned and... still does not work.

1. I deleted all providers
2. i waited until i see the message "Provider tidal--9otPcKHg removed from library"
3. then i restarted the addon from HA
4. i added the tidal integration again
5. after sync was completed, only the same 48 tracks was loaded 

![Image](https://github.com/user-attachments/assets/1600c2de-fd37-480e-b90c-cef3bfd3d3f4)

Note: i checked if my AdGuardHome was blocking some domain related with tidal but, not

![Image](https://github.com/user-attachments/assets/e31ac1e9-3309-4b80-b919-21d6d14cd95b)

**Comment by jozefKruszynski** [comment]
I'd say there is clearly something funky going on, I'll look into it as soon as I can, but I'm on holiday until the last week of June.

**Comment by jozefKruszynski** [comment]
Definitely something odd in the 2.5.4 release version.

Just switched to that release tag on my dev machine and did a completely new sync

<img width="273" alt="Image" src="https://github.com/user-attachments/assets/e0026a0d-2fb5-4d64-ad6e-850aac75e99f" />

No log messages of any kind pointing to anything strange so this is gonna be a fun one.

**Comment by cmonrroy88** [comment]
Maybe any change on Tidal API? It was working fine just before that I report the issue

**Comment by jozefKruszynski** [comment]
I might have a few spare minutes today before I set off for the second part of my holidays. We'll see if I can find the issue.

**Comment by jozefKruszynski** [comment]
I've fixed this locally. I'll push a PR today. I'm amazed I didn't catch this previously. Very stupid error on my part.

**Comment by cmonrroy88** [comment]
I updated MA to 2.5.5 but, the issue persist after add tidal as music provider and sync, now I see 50 tracks.

Do I need to perform any other action to get it to work?

![Image](https://github.com/user-attachments/assets/be45396a-069f-4d7f-a33d-7557bf9780cd)

**Comment by jozefKruszynski** [comment]
The fix was only merged in today and has not yet been released

**Comment by SteffanDonal** [comment]
Confirmed fixed for me in the new beta 👍
