### ISSUE TITLE
Tracks played to Sonos players not recorded as played

### ISSUE THREAD

**Issue by Laflamme** [music-assistant/support#4125]
### What version of Music Assistant has the issue?

2.6.0b14 and 2.5.5, but I have been having this issue for several releases

### How is the MA server installed?

Home Assistant OS Addon

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

When I play music from any Music Provider to the Sonos provider with Airplay mode disabled on the players, tracks are not recorded as played:
- They do not show up in the Recently Played section of the Home Screen.
- They are not taken into account when sorting tracks by Last played or Play count in the library.
- They are not taken into account when calling the Get Library Items action in Home Assistant with the Order by Last played or Play count options enabled.
- They do not trigger a scrobble using the Subsonic Scrobble plugin.

As a result, my Recently Played Tracks Music Assistant playlist remains empty.

If I add an album, an artist or a playlist to the queue, it records that album, artist or playlist immediately, but none of the individual tracks as they are played.

Very rarely, a tracks does get recorded as it's supposed to be.

### How to reproduce

Play music from any Music Provider to the Sonos provider.

### Music Providers

Problem reproduced with: 
- OpenSubsonic Media Server Library
- Filesystem local disk
- Jellyfin Media Server Library
- Apple Music

### Player Providers

This issue appears to be specific to the Sonos player provider.

My setup:
- Beam (wired) + One + One + Sub Mini
- One (wired) + One SL (wired)
- One 

I do not encounter this issue using the Music Assistant Web Interface Player (tracks get recorded).

Enabling Airplay mode on Sonos players appears to solve the issue, but introduces another one: Airplay as an external source tries to steal the players when I start a new queue, leading to multiple queue restarts.

### Full log output

Sorry about the cover image errors flooding the log.

[music-assistant.log](https://github.com/user-attachments/files/21328005/music-assistant.log)

### Additional information

I have tried fresh installs using both the Home Assistant OS Addon, and the Docker Container on a different machine.

As a workaround, I was hoping to use Subsonic Scrobble and keep track of played tracks externally, but whatever prevents tracks to be recorded in Music Assistant also prevents them to be scrobbled.

### What version of Home Assistant Core are your running

2025.7.2 (but this has been an issue on previous releases)

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

### Have you included ALL of the information specified in the Troubleshooting FAQ or explained why you cannot

- [x] Yes

**Comment by marcelveldt** [comment]
Can you please re-test this using the latest beta (or stable) release ?

**Comment by Laflamme** [comment]
Thank you for looking into this! Unfortunately, this issue remains on 2.6.0b17.

**Comment by OzGav** [comment]
This has been fixed in b18

**Comment by Laflamme** [comment]
I'm currently on 2.7.0 beta 2 and this is still an issue. I just listened to 22 songs and none of them were recognized as played. 

I tried 2.7.0 beta 3 when it was released, but I had to revert back to beta 2 because of several issues: most notably, normalization seemed to be applied twice to songs that had embedded ReplayGain tags, making them very quiet, and playback would often stop after one song. I'm sorry I didn't raise those issues: I didn't have a lot of time to investigate them before having to revert back. I'll try to fill a proper report if I encounter them again with beta 4.

**Comment by hosh0815** [comment]
Version: 2.7.0b8 
here is the played Tracks: shown from the last.fm integration: 

Twilight - I Wonder Who | 01.11.2025 10:00
-- | --
Sharon Ridley - Changin' | 01.11.2025 10:04
Curtis Mayfield - You're So Good To Me | 01.11.2025 10:10
The Whispers - Don't Keep Me Waiting | 01.11.2025 10:17
Herbie Hancock - Making Love | 01.11.2025 10:21
Roy Ayers Ubiquity - Keep on Walking | 01.11.2025 10:27
Michael Wycoff - Love Conquers All | 01.11.2025 10:31
Fats Gaines Band - For Your Love | 01.11.2025 10:36
Graham Central Station - Is It Love? | 01.11.2025 10:41
Lyn Christopher - Take Me With You | 01.11.2025 10:47
Family Circle - Mariya | 01.11.2025 10:50
Windy City - Win or Lose | 01.11.2025 10:54
The Undisputed Truth - Ungena Za Ulimwengu (Unite The World) | 01.11.2025 10:57
Jeannie Reynolds - You Want To Get Your Hands On A Woman | 01.11.2025 11:06
Chocolate Milk - Girl Callin' | 01.11.2025 11:10
Trama - If I Ever Do Wrong | 01.11.2025 11:15
J. Kelly And The Premiers - She Calls Me Baby | 01.11.2025 11:19
Edwin Starr - Easin' In | 01.11.2025 11:22
Roy Ayers Ubiquity - Baby You Give Me a Feeling | 01.11.2025 11:26
L.A. Boppers - You Did It Good | 01.11.2025 11:28
Stevie Wonder - All Day Sucker | 01.11.2025 11:33
Fatback Band - Mister Bass Man | 01.11.2025 11:38
The Nite-Liters - Funky-Vamp | 01.11.2025 11:41
Milton Wright - Magic Music | 01.11.2025 11:46
Edward Fisher - I Feel Good | 01.11.2025 11:49
John Heartsman & Circles - Mr. Magic | 01.11.2025 11:53
Roy Porter Sound Machine - Jessica (instrumental) | 01.11.2025 11:58
Ian Carr - Summer Rain | 01.11.2025 12:05
24-Carat Black - Ghetto: Misfortune's Wealth | 01.11.2025 12:12
Skip Mahoney & the Casuals - I need your love | 01.11.2025 12:15
Congress Alley - Are You Looking? | 01.11.2025 12:22
Mutiny - The Ballad Of Capt. Hymbad | 01.11.2025 12:26
Merry Clayton - Emotion | 01.11.2025 12:29
Manchild - Especially For You | 01.11.2025 12:34
Mandré - Wonder What I'd Do | 01.11.2025 12:40
Collage - Love Is for Everyone | 01.11.2025 12:44
Ebony Rhythm Funk Campaign - Syncopated Madness | 01.11.2025 12:49
The Four Tops - Strung Out For Your Love | 01.11.2025 12:55
William Stuckey - The first time | 01.11.2025 13:00

and heres the result on the last.fm site... 

<img width="826" height="563" alt="Image" src="https://github.com/user-attachments/assets/d010d260-0d6d-492a-bbf4-0b81d71a7cc4" />

don´t know what you need more

[d5369777_music_assistant_beta_2025-11-01T13-09-54.752Z.log](https://github.com/user-attachments/files/23283039/d5369777_music_assistant_beta_2025-11-01T13-09-54.752Z.log)

**Comment by OzGav** [comment]
@hosh0815 This issue is not about last.fm please remove your post and open a discussion.

**Comment by Laflamme** [comment]
Thank you @marcelveldt for your help!

I just upgraded from 2.7.0 beta 2 to 2.7.0 beta 8 this morning. The playback and normalization secondary issues I briefly mentioned having with 2.7.0 beta 3 seem to have been fixed indeed, but the main issue still remains.

I am using the Music Assistant player provider for Sonos, not the Sonos integration in HA.

Instead of  "recorded as played", maybe I should have said "registered as played", or "recognized as played"? Sorry about that. Here is what I mean:

When I use another player provider, for instance the Builtin Web Player, and play the 500 Random track (form library) playlists, whenever a track finishes playing, it shows up in the Recently played section of the Home view. It also shows up if I go to the Tracks view and sort by Last played (descending), and the same track shows up once again if I use the music_assistant.get_library action in Home Assistant and set the order_by parameter to " last_played_desc".

When I do exactly the same things using the Sonos player provider, when a track finishes playing, Music Assistant doesn't seem to register that it has been played. 

The track doesn't show up in the Recently played section of the Home view, doesn't show up if I go to the Tracks view and sort by Last played (descending), and doesn't show up if  I use the music_assistant.get_library action in Home Assistant and set the order_by parameter to " last_played_desc". As far as Music Assistant is concerned, it is as if I hadn't played that track.

For a I while, I was under the impression that manually interacting with a track (skipping back to the previous track and letting it finish again, for instance) worked around the issue, but more testing indicates that it is not the case. Every once in a while, a track is just properly recognized as played, seemingly at random, no matter if I interact with it or not.

**Comment by Laflamme** [comment]
Has the _Enable queue flow mode toggle_ been added to Sonos players recently? I'm almost certain it wasn't there when I looked for it several releases ago. I just enabled it and thus far every track I have played has been properly recognized as played.

**Comment by marcelveldt** [comment]
You can temporary use flow mode on Sonos (at the cost of the Sonos app no longer showing what is playing) until the issue is resolved

**Comment by ajacques** [comment]
* Version: 2.7.6 
*  Which providers do you have enabled? **fanart.tv, Jellyfin, ListenBraizn Scrobbler, LRCLIB, Music Assistant, MusicBrainz, Sendspin, SONOS, The Audio DB**
*  Which do you use for playback? Local provider? Remote / SMB provider? **Jellyfin**
*  Sonos S1 or Sonos provider? **Sonos Provider**
*  Which Sonos speaker model do you use? *Mixture of Sonos Ones and Play:1s*

I'm using the ListenBrainz scrobbler and I also see very inconsistent scrobbling. The now playing feature on ListenBrainz is always up to date (with a ~10 second delay or so), but the actual plays rarely ever get reflected. 

Checking the debug logs, I see this when the first song ends and the next one starts:


```
2026-02-12 03:42:19.845 DEBUG (MainThread) [music_assistant.listenbrainz_scrobble] reset _last_scrobbled and _currently_playing because the song was restarted
2026-02-12 03:42:20.935 DEBUG (MainThread) [music_assistant.players] Handling command enqueue_next_media for player Media Room (unauthenticated)
2026-02-12 03:42:50.923 DEBUG (ThreadPoolExecutor-0_6) [music_assistant.listenbrainz_scrobble] track library://track/172 marked as 'now playing'
2026-02-12 03:42:50.923 DEBUG (MainThread) [music_assistant.listenbrainz_scrobble] track library://track/172 marked as 'now playing'
2026-02-12 03:45:10.705 DEBUG (MainThread) [music_assistant.players] Handling command enqueue_next_media for player Media Room (unauthenticated)
2026-02-12 03:45:41.110 DEBUG (ThreadPoolExecutor-0_14) [music_assistant.listenbrainz_scrobble] track library://track/316 marked as 'now playing'
2026-02-12 03:45:41.110 DEBUG (MainThread) [music_assistant.listenbrainz_scrobble] track library://track/316 marked as 'now playing'
````

I didn't have any songs on repeat. And of course as I was writing this, a bunch of songs got scrobbled to ListenBrainz. I can't tell if it's because of delayed ListenBrainz processing or if Music Assistant got delayed sending them

**Comment by MarvinSchenkel** [comment]
I finally may have found the root cause here. 2.8.1 has been released with a fix. Could you please test and verify this?

**Comment by Laflamme** [comment]
It was already working with Queue Flow Mode enabled, and I confirm that it now works with Queue Flow mode disabled as well. Thank you for your work on this!
